name: stacked_architectiure
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  auto_route: ^3.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.1
  get_it: ^7.2.0
  injectable: ^1.5.0
  provider: ^6.0.2
  stacked: ^2.2.7+1
  stacked_services: ^0.8.16
  salomon_bottom_bar: ^3.2.0


dev_dependencies:
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.0

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
